name: Check & Build No Cache

on:
  workflow_dispatch:
  # schedule:
    # - cron: "*/30 * * * *"

jobs:
  mac_build:
    name: Mac OS Build
    runs-on: macos-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: make build

  ubuntu_build:
    name: Ubuntu OS Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: make build
