name: Check & Build No Cache

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  docker_build:
    name: Docker Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build-cdc
        run: docker build -f ./deployments/ticdc/docker/Dockerfile .

      - name: Build-dm
        run: docker build -f ./dm/Dockerfile .

      - name: Build-engine
        run: docker build -f ./deployments/engine/docker/Dockerfile .

  mac_build:
    name: Mac OS Build
    runs-on: macos-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Build
        run: make build
